import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "@/ui/molecules/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Skateshop",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="pl">
			<body className={inter.className}>
				<div className="flex flex-col">
					<Navbar />
					<section className="flex-shrink  pb-10">{children}</section>
					<footer className="mt-6 text-center text-xl">@ 2023</footer>
				</div>
			</body>
		</html>
	);
}
